### ISSUE TITLE
[jupyterbook-latex]inserted graphs' layout

### ISSUE THREAD

**Issue by sayaikegawa** [QuantEcon/lecture-python.myst#75]
Hi @AakashGfude ,

This is an issue that inserted graphs are shown in different places as follows.
Left:```jupyter-book``` Right:```website```

![Screen Shot 2021-02-03 at 8 40 52 pm](https://user-images.githubusercontent.com/44494439/106728892-082d9d00-6661-11eb-8e1e-b00e922faf06.png)

**Comment by AakashGfude** [comment]
Hey @sayaikegawa thanks for pointing this out. 

Actually, this is not an issue, as the image would have been placed in the same place if there was space for it.  But since in the left document, there is not enough space for that image to be there. It is instead replaced by text as it would have resulted in a large blank space which will not look good.

For cases, where there is enough space to include the image like in the right screenshot above, it should behave as intended.

**Comment by AakashGfude** [comment]
feel free to close the issue if you are satisfied with the answer :) let me know if you have any queries regarding this.

**Comment by sayaikegawa** [comment]
Thank you @AakashGfude . I understand and close this issue.
