### ISSUE TITLE
[jupyterbook-latex] [wald_friedman] an inserted figure missing in both PDFs generated by myst and rst

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#88]
Hi @AakashGfude and @mmcky , the 2nd issue I noticed is that in lecture [wald_friedman](https://python.quantecon.org/wald_friedman.html) both PDFs generated by ``myst`` and ``rst``
- an inserted figure is missing.

Please see (top left: PDFs generated by ``rst``, top right: PDFs generated by ``myst``, bottom: website):

![Screen Shot 2021-02-11 at 4 35 59 am](https://user-images.githubusercontent.com/53931041/107548411-b964a200-6c22-11eb-8538-55e59f5959b1.png)

**Comment by mmcky** [comment]
@AakashGfude the fact this is missing in `both` suggests the image might be an unsupported format for latex?

**Comment by AakashGfude** [comment]
@mmcky @shlff seems to be coming up in the latest build. probably was fixed by one of the merged PRs ?

<img width="915" alt="Screen Shot 2021-02-15 at 11 47 09 pm" src="https://user-images.githubusercontent.com/6542997/107948547-1fb54000-6fe8-11eb-9f8b-91a38ac82afa.png">


[python.pdf](https://github.com/QuantEcon/lecture-python.myst/files/5981581/python.pdf)

**Comment by AakashGfude** [comment]
Will close this issue. As it seems to be resolved.
