### ISSUE TITLE
[jupyterbook-latex] mistakenly treat "Troubleshooting" and "Reference" as chapter 58 and chapter 59

### ISSUE THREAD

**Issue by shlff** [QuantEcon/lecture-python.myst#98]
Hi @AakashGfude and @mmcky , I find that in the PDFs of myst-version lectures, we mistakenly treat "Troubleshooting" and "Reference" as chapter 58 and chapter 59, respectively.

Please see the screenshot:
![Screen Shot 2021-02-11 at 9 03 48 am](https://user-images.githubusercontent.com/53931041/107578640-1a52a100-6c48-11eb-9a52-0551421c6cdb.png)

and

![Screen Shot 2021-02-11 at 9 04 01 am](https://user-images.githubusercontent.com/53931041/107578647-1cb4fb00-6c48-11eb-975c-2ce42cb552ce.png)

**Comment by mmcky** [comment]
@AakashGfude I don't see a way to add non-numbered chapters at the moment but would be nice feature to have in the future.

**Comment by shlff** [comment]
I just noticed that there is no contexts under the Reference chapter but there is a section ``BIBLIOGRAPHY`` after ``Execution Statistics``, which is after ``References``. 

Please find the pdf here: 

https://python.quantecon.org/_pdf/quantecon-python.pdf

**Comment by mmcky** [comment]
We won't fix this in the current `jupyter-book` as we are about to migrate to `MystMD`  soon. 

This is due to `references.md` containing the directive to list the references on the `html` website, but in the `pdf` context this is an empty page as it uses a Bibliography section at the end of the document.
